exception handling using try and except method

num1 = (input("Enter the 1 number : "))
num2 = (input("Enter the 2 number : "))

try:
    print("sum of two numbers is  : ",int(num1)+int(num2))
except Exception as e:
    print(e)
print("this line is very inportant")